export const users = [
  {
    id: "1",
    name: "John Doe",
    email: "john@university.edu",
    status: "active",
    role: "student",
    lastActive: "Today, 2:30 PM",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "JD",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@university.edu",
    status: "active",
    role: "student",
    lastActive: "Today, 1:15 PM",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "JS",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@university.edu",
    status: "inactive",
    role: "student",
    lastActive: "Yesterday",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "MJ",
  },
  {
    id: "4",
    name: "Sarah Williams",
    email: "sarah@university.edu",
    status: "active",
    role: "faculty",
    lastActive: "Today, 10:30 AM",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "SW",
  },
  {
    id: "5",
    name: "Alex Brown",
    email: "alex@university.edu",
    status: "active",
    role: "admin",
    lastActive: "Today, 9:45 AM",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "AB",
  },
]

