export const timetables = [
  {
    id: "1",
    name: "Computer Science - Year 1",
    department: "Computer Science",
    semester: "Fall",
    year: "2023",
    status: "published",
    lastUpdated: "2023-08-15",
  },
  {
    id: "2",
    name: "Computer Science - Year 2",
    department: "Computer Science",
    semester: "Fall",
    year: "2023",
    status: "published",
    lastUpdated: "2023-08-14",
  },
  {
    id: "3",
    name: "Electrical Engineering - Year 1",
    department: "Electrical Engineering",
    semester: "Fall",
    year: "2023",
    status: "draft",
    lastUpdated: "2023-08-10",
  },
  {
    id: "4",
    name: "Business Administration - Year 3",
    department: "Business",
    semester: "Fall",
    year: "2023",
    status: "published",
    lastUpdated: "2023-08-12",
  },
  {
    id: "5",
    name: "Psychology - Year 2",
    department: "Psychology",
    semester: "Fall",
    year: "2023",
    status: "draft",
    lastUpdated: "2023-08-05",
  },
]

