version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: arupaka
      POSTGRES_PASSWORD: arupaka
      POSTGRES_DB: arupaka_db_manager

  nestjs:
    build:
      context: ./nestjs
    container_name: nestjs
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    env_file:
      - .env.docker
    volumes:
      - ./nestJS:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm run dev"
    restart: always
