version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: arupaka
      POSTGRES_PASSWORD: arupaka
      POSTGRES_DB: arupaka_db_manager
      POSTGRES_HOST_AUTH_METHOD: trust

  postgres_python:
    image: postgres:14
    container_name: postgres_python
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: arupaka
      POSTGRES_PASSWORD: arupaka
      POSTGRES_DB: arupaka_db_manager_python

