export const classes = [
  {
    id: "1",
    code: "CS101",
    name: "Introduction to Computer Science",
    instructor: "Dr. John Smith",
    department: "Computer Science",
    schedule: "MWF 10:00 AM - 11:15 AM",
    room: "Tech Building 101",
    capacity: 30,
    enrolled: 28,
    status: "active",
  },
  {
    id: "2",
    code: "MATH201",
    name: "Calculus I",
    instructor: "Dr. Sarah Johnson",
    department: "Mathematics",
    schedule: "TR 9:30 AM - 10:45 AM",
    room: "Science Hall 205",
    capacity: 35,
    enrolled: 35,
    status: "full",
  },
  {
    id: "3",
    code: "ENG102",
    name: "Composition and Rhetoric",
    instructor: "Prof. Michael Brown",
    department: "English",
    schedule: "MWF 1:00 PM - 2:15 PM",
    room: "Humanities 302",
    capacity: 25,
    enrolled: 18,
    status: "active",
  },
  {
    id: "4",
    code: "PHYS101",
    name: "Introduction to Physics",
    instructor: "Dr. Emily Davis",
    department: "Physics",
    schedule: "TR 2:00 PM - 3:15 PM",
    room: "Science Hall 110",
    capacity: 30,
    enrolled: 12,
    status: "cancelled",
  },
  {
    id: "5",
    code: "BUS301",
    name: "Business Ethics",
    instructor: "Prof. Robert Wilson",
    department: "Business",
    schedule: "MW 3:30 PM - 4:45 PM",
    room: "Business Building 201",
    capacity: 40,
    enrolled: 38,
    status: "active",
  },
]

