export const textbooks = [
  {
    id: "1",
    title: "Introduction to Computer Science",
    author: "John Smith",
    course: "CS101",
    price: 75.99,
    condition: "like new",
    seller: "Alex Johnson",
    listedDate: "2023-08-10",
    status: "available",
  },
  {
    id: "2",
    title: "Calculus: Early Transcendentals",
    author: "James Stewart",
    course: "MATH201",
    price: 89.99,
    condition: "good",
    seller: "Sarah Williams",
    listedDate: "2023-08-05",
    status: "pending",
  },
  {
    id: "3",
    title: "Principles of Economics",
    author: "N. Gregory Mankiw",
    course: "ECON101",
    price: 65.5,
    condition: "new",
    seller: "Michael Brown",
    listedDate: "2023-08-12",
    status: "available",
  },
  {
    id: "4",
    title: "Introduction to Psychology",
    author: "David G. Myers",
    course: "PSYC101",
    price: 55.0,
    condition: "fair",
    seller: "Emily Davis",
    listedDate: "2023-07-28",
    status: "sold",
  },
  {
    id: "5",
    title: "Organic Chemistry",
    author: "Paula Y. Bruice",
    course: "CHEM301",
    price: 95.75,
    condition: "good",
    seller: "Ryan Wilson",
    listedDate: "2023-08-08",
    status: "available",
  },
]

