export const rooms = [
  {
    id: "1",
    name: "Room 101",
    building: "Tech Building",
    capacity: 30,
    type: "lecture",
    features: ["projector", "whiteboard", "computer"],
    status: "available",
    schedule: "MWF 10:00 AM - 11:15 AM",
  },
  {
    id: "2",
    name: "Room 205",
    building: "Science Hall",
    capacity: 35,
    type: "lab",
    features: ["lab equipment", "computers", "smartboard"],
    status: "occupied",
    schedule: "TR 9:30 AM - 10:45 AM",
  },
  {
    id: "3",
    name: "Room 302",
    building: "Humanities",
    capacity: 25,
    type: "seminar",
    features: ["projector", "whiteboard", "roundtable"],
    status: "available",
    schedule: "MWF 1:00 PM - 2:15 PM",
  },
  {
    id: "4",
    name: "Room 110",
    building: "Science Hall",
    capacity: 30,
    type: "lecture",
    features: ["projector", "whiteboard", "computer"],
    status: "maintenance",
    schedule: "TR 2:00 PM - 3:15 PM",
  },
  {
    id: "5",
    name: "Room 201",
    building: "Business Building",
    capacity: 40,
    type: "lecture",
    features: ["projector", "whiteboard", "computer", "microphone"],
    status: "available",
    schedule: "MW 3:30 PM - 4:45 PM",
  },
]

