# Generated by Django 5.0 on 2025-02-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kamoku',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('classCode', models.IntegerField()),
                ('name', models.CharField(max_length=400)),
                ('classroom', models.CharField(max_length=400)),
                ('teacher', models.CharField(max_length=400)),
                ('syllabus', models.CharField(max_length=400)),
                ('weekday', models.CharField(max_length=400)),
                ('period', models.IntegerField()),
                ('academic', models.CharField(max_length=400)),
                ('credits', models.IntegerField()),
                ('semester', models.CharField(max_length=400)),
            ],
        ),
    ]
