# Generated by Django 5.0 on 2025-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamoku',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
