# Generated by Django 5.0 on 2025-03-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_kamoku_campus_alter_kamoku_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kamoku',
            new_name='Lecture',
        ),
    ]
