# Generated by Django 5.0 on 2025-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_rename_kamoku_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='category',
            field=models.CharField(default='Null', max_length=400),
        ),
    ]
