# Generated by Django 5.0 on 2025-03-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_lecture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
