# Generated by Django 5.0 on 2025-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_kamoku_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamoku',
            name='schoolYear',
            field=models.IntegerField(null=True),
        ),
    ]
