# Generated by Django 5.0 on 2025-03-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_kamoku_schoolyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamoku',
            name='campus',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='kamoku',
            name='semester',
            field=models.BooleanField(default=False),
        ),
    ]
