export const carouselItems = [
  {
    id: "1",
    title: "Welcome to Fall Semester",
    description: "Important information for new and returning students",
    imageUrl: "/placeholder.svg?height=400&width=800",
    targetUrl: "/welcome",
    position: 1,
    status: "active",
    createdAt: "2023-08-01",
  },
  {
    id: "2",
    title: "Campus Events",
    description: "Check out upcoming events and activities on campus",
    imageUrl: "/placeholder.svg?height=400&width=800",
    targetUrl: "/events",
    position: 2,
    status: "active",
    createdAt: "2023-08-05",
  },
  {
    id: "3",
    title: "Library Hours",
    description: "Updated library hours for the fall semester",
    imageUrl: "/placeholder.svg?height=400&width=800",
    targetUrl: "/library",
    position: 3,
    status: "active",
    createdAt: "2023-08-10",
  },
  {
    id: "4",
    title: "Career Fair",
    description: "Annual career fair coming next month",
    imageUrl: "/placeholder.svg?height=400&width=800",
    targetUrl: "/career-fair",
    position: 4,
    status: "inactive",
    createdAt: "2023-07-25",
  },
  {
    id: "5",
    title: "Sports Schedule",
    description: "Check out the upcoming sports events",
    imageUrl: "/placeholder.svg?height=400&width=800",
    targetUrl: "/sports",
    position: 5,
    status: "inactive",
    createdAt: "2023-07-20",
  },
]

