name: Create Develop to Main PR After Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

permissions:
  pull-requests: write
  contents: read

jobs:
  create-develop-to-main-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check if a develop-to-main PR already exists
        id: check_pr
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              base: "main",
              head: "develop",
            });

            if (prs.data.length > 0) {
              core.setOutput("pr_exists", "true");
            } else {
              core.setOutput("pr_exists", "false");
            }

      - name: Create a PR from develop to main
        if: steps.check_pr.outputs.pr_exists == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: "${{ github.event.pull_request.title }} -stgテスト"
          body: "${{ github.event.pull_request.body }}"
          base: main
          branch: develop
          draft: false

      - name: Add label to the created PR
        if: steps.check_pr.outputs.pr_exists == 'false'
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          script: |
            const prNumber = Number('${{ steps.create_pr.outputs.pr_number }}');

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ["stg-test"]  // ← ここで好きなラベル名を指定
            });

      - name: Fail if develop-to-main PR already exists
        if: steps.check_pr.outputs.pr_exists == 'true'
        run: |
          echo "Error: A develop-to-main PR already exists."
          exit 1
