name: deploy website

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "admin-site/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js & pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "admin-site/pnpm-lock.yaml"

      - name: Install dependencies & build
        working-directory: ./admin-site
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to Vercel
        id: vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
          working-directory: ./admin-site

      - name: Comment Vercel Preview URL
        if: github.ref == 'refs/heads/develop' && github.event.head_commit.message != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prList = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:develop`,
              state: 'closed'
            });

            const mergedPR = prList.data.find(pr => pr.merged_at);
            if (mergedPR) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: mergedPR.number,
                body: `🚀 Vercel Preview 環境: ${{ steps.vercel.outputs.preview-url }}`
              });
            } else {
              console.log('No merged PR found on develop branch.');
            }
