# .github/workflows/deploy.yml
name: deploy website

# main ブランチの admin-site 配下変更時／手動実行でトリガー
on:
  push:
    branches:
      - main
    paths:
      - 'admin-site/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリ全体を checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) pnpm CLI を先にセットアップ（v4 を使用）
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      # 3) Node.js 環境をセットアップ＆pnpm キャッシュを有効化
      - name: Setup Node.js & pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: 'admin-site'   # ← これで admin-site/pnpm-lock.yaml を参照

      # 4) admin-site 配下で依存インストール＆ビルド
      - name: Install dependencies & build
        working-directory: ./admin-site
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      # 5) Vercel へデプロイ
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token:       ${{ secrets.VERCEL_TOKEN }}
          vercel-args:        '--prod'
          vercel-org-id:      ${{ secrets.ORG_ID }}
          vercel-project-id:  ${{ secrets.PROJECT_ID }}
          working-directory:  ./admin-site
