name: deploy website
on:
  push:
    branches:
      - main
    paths:
      - 'admin-site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリをチェックアウト（main ブランチが自動で取られます）
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Node.js 環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. admin-site フォルダ内でインストール＆ビルド
      - name: Build admin-site
        working-directory: ./admin-site
        run: |
          npm ci
          npm run build

      # 4. Vercel へデプロイ
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token:      ${{ secrets.VERCEL_TOKEN }}
          vercel-args:       '--prod'
          vercel-org-id:     ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./admin-site

